# Issue templates for better issue management
name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: test-type
    attributes:
      label: Test Type
      description: What type of test is failing?
      options:
        - UI Test
        - API Test
        - Both
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment did this occur?
      options:
        - Production
        - QA
        - UAT
        - All
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are affected?
      options:
        - Chromium
        - Firefox
        - WebKit
        - All
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen
      placeholder: A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: test-output
    attributes:
      label: Test Output/Error
      description: Copy and paste the test output or error message
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
