name: Playwright Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_VERSION: "18"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run API tests
        run: ENV=prod npm run test:api
        env:
          CI: true
        continue-on-error: true

      - name: Run UI tests
        run: ENV=prod npm run test:ui
        env:
          CI: true
        continue-on-error: true

      - name: Generate HTML report
        if: always()
        run: npx playwright show-report || echo "No report to show"

      - name: List generated files (debug)
        if: always()
        run: |
          echo "🔍 Checking for generated files..."
          ls -la || true
          echo "📁 Playwright report directory:"
          ls -la playwright-report/ || echo "playwright-report/ not found"
          echo "📁 Test results directory:"
          ls -la test-results/ || echo "test-results/ not found"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            playwright-report/**/*
            test-results/**/*
          retention-days: 7
          if-no-files-found: warn
